### ISSUE TITLE
register does not work with nyc

### ISSUE THREAD

**Issue by mourner** [leebyron/flow-remove-types#15]
Using `nyc` to instrument test coverage of flow-typed code, this fails:

```bash
nyc --require=flow-remove-types/register npm test
# failed to instrument code ... (complains about a flow type)
```

On the other hand, using `babel-register` with `babel-plugin-transform-flow-strip-types` works:

```bash
nyc --require=babel-register npm test
```

I noticed a comment in `register.js` — could it be this difference (`Module.prototype._compile` vs `require.extensions`) that prevents `nyc` from working? And would you accept a PR that switches register mechanism to `require.extensions`?

cc @leebyron

**Comment by leebyron** [comment]
Unfortunately there's no good way to register a require hook. It was changed away from require.extensions to Module#_compile recently to solve other issues. If this is truly the only way to fix the underlying issue, perhaps a configuration flag can be passed to register, I'd consider something like that.

Though I would be surprised if that was the fix, since the default require.extensions simply calls through to Module#_compile, and _compiles gives us the ability to support multiple register hooks.

Could you give some more information about what's going wrong or perhaps if you've done any investigation, then share where in the `nyc` codebase this is causing issues? Perhaps there's a fix that's better for everyone somewhere.

**Comment by mourner** [comment]
Yep, I confirmed that reverting https://github.com/leebyron/flow-remove-types/commit/3ecc215f5f5cc433af4c60d03af65daa63244450 makes `nyc` work.

I'm not sure why the new approach doesn't work with `nyc`. Perhaps @bcoe could weigh in on the matter?

**Comment by mourner** [comment]
@leebyron I worked around the issue by using a custom `register` script with the old behavior (see https://github.com/mapbox/mapbox-gl-js/pull/3539).

By the way, thanks a lot for this project — it's wonderful! Before I managed to get this to work, I tried switching to babel, but our huge test-suite (6m+) would run at least 3-5 times slower with it (couldn't wait until the end to measure). `flow-remove-types` saves the day!

**Comment by bcoe** [comment]
@leebyron in `nyc` and `ava` we've been using this abstraction:

https://github.com/istanbuljs/append-transform

It takes a lot of the annoyance around registering a require hook; and it ensures that multiple require hooks can be registered at the same time. Would love your thoughts on this abstraction.

@mourner., @leebyron having said this; the goal with `nyc` is to make it as _magic_ as possible (in the good sense of that word, not the impossible to maintain codebase sense of that word) I wonder if we should discuss adding support for `_compile`.

**Comment by leebyron** [comment]
I've got a technique going based on the `pirates` npm module that I've verified *mostly* works along Babel and other require-hook services - at least as well as it was working before, but should also work with `nyc` and `ava`.

@bcoe - you should consider hooking `Module.prototype._compile` as a better guarantee for running last, since the existing state of `flow-remove-types`'s require hook illustrates a way to go further last than append-transform :)
