### ISSUE TITLE
flow-remove-types/register with modules

### ISSUE THREAD

**Issue by druide** [leebyron/flow-remove-types#17]
I have a module using Flow in source `/* @flow*/` and `require('flow-remove-types/register');`. It works standalone. Then I use this module in application which is using Flow too (`/* @flow*/` and `require('flow-remove-types/register');`). Got a syntax error, because in `register.js` we have:

```
  var transformedSource = filename.indexOf('node_modules/') === -1
    ? removeTypes(source)
    : source;
```

and module's file sources are not processed, as their filenames contains 'node_modules/'.  
What about to compile unconditionally?

```
var transformedSource = removeTypes(source);
```

P.S. Ubuntu 14, Node.js 6.9.1.

**Comment by leebyron** [comment]
Hey thanks for the report. This is intentional since `npm` recommends distributing plain JS code in order to not require users of your module to use transformers. As a result, `flow-remove-types/register` is a development time technique only, and not meant for distributed code.

That's because it takes a small amount of time to transform a file, which may be okay for your application code, but could add up quickly if you include many files in node_modules, which is quite common. That would lead to slow execution times.

Also, the register hook alters the global state which is okay for your application, but wouldn't be acceptable when loading in a library.

Before distributing code on npm, make sure you run `flow-remove-types` to produce the transformed output.

**Comment by jleppert** [comment]
There's a special place in hell reserved for people who add proprietary extensions to javascript, and typing to a dynamic language with no runtime validation.
